In [1]:
import pandas as pd
import numpy as np

In [4]:
orders = pd.read_csv('../restaurant-data/data/20201203/OrderDetails.csv')
items = pd.read_csv('../restaurant-data/data/20201203/AllItemsReport.csv')

In [39]:
orders.shape

(11, 24)

In [14]:
items.columns

Index(['Master ID', 'Item ID', 'Parent ID', 'Menu Name', 'Menu Group',
       'Subgroup', 'Menu Item', 'Avg Price', 'Item Qty (incl voids)',
       '% of Ttl Qty (incl voids)', 'Gross Amount (incl voids)',
       '% of Ttl Amt (incl voids)', 'Item Qty', 'Gross Amount', 'Void Qty',
       'Void Amount', 'Discount Amount', 'Net Amount', '# Orders',
       '% of Ttl # Orders', '% Qty (Group)', '% Qty (Menu)', '% Qty (All)',
       '% Net Amt (Group)', '% Net Amt (Menu)', '% Net Amt (All)'],
      dtype='object')

In [16]:
items

,Master ID,Item ID,Parent ID,Menu Name,Menu Group,Subgroup,Menu Item,Avg Price,Item Qty (incl voids),% of Ttl Qty (incl voids),...,Discount Amount,Net Amount,# Orders,% of Ttl # Orders,% Qty (Group),% Qty (Menu),% Qty (All),% Net Amt (Group),% Net Amt (Menu),% Net Amt (All)
0,NaN,NaN,NaN,ALL MENUS,NaN,NaN,NaN,9.561404,57.0,0.000000,...,17.6,527.4,10,0.000000,0.0,0.0000,0.000000,0.0,0.00000,0.000000
1,NaN,NaN,NaN,DRINKS,NaN,NaN,NaN,8.187500,32.0,0.561404,...,5.8,256.2,9,0.900000,0.0,0.0000,0.561404,0.0,0.00000,0.485779
2,2.000000e+17,2.000000e+17,NaN,DRINKS,Drinks,NaN,NaN,3.500000,2.0,0.062500,...,0.6,6.4,2,0.222222,0.0,0.0625,0.035088,0.0,0.02498,0.012135
3,2.000000e+17,2.000000e+17,2.000000e+17,DRINKS,Drinks,NaN,Pepsi,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.0,0.0000,0.000000,0.0,0.00000,0.000000
4,2.000000e+17,2.000000e+17,2.000000e+17,DRINKS,Drinks,NaN,Diet Pepsi,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.0,0.0000,0.000000,0.0,0.00000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,0.000000e+00,0.000000e+00,-1.000000e+00,Gift Cards,Gift Cards,NaN,Classic Gift Card,50.000000,2.0,1.000000,...,0.0,100.0,1,1.000000,1.0,1.0000,0.035088,1.0,1.00000,0.189609
456,NaN,NaN,NaN,Open Items,NaN,NaN,NaN,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.0,0.0000,0.000000,0.0,0.00000,0.000000
457,-2.000000e+17,-2.000000e+17,NaN,Open Items,Open Food,NaN,NaN,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.0,0.0000,0.000000,0.0,0.00000,0.000000
458,-2.000000e+17,-2.000000e+17,NaN,Open Items,Open Liquor,NaN,NaN,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.0,0.0000,0.000000,0.0,0.00000,0.000000
459,-2.000000e+17,-2.000000e+17,NaN,Open Items,Open Beer,NaN,NaN,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.0,0.0000,0.000000,0.0,0.00000,0.000000

In [31]:
items['Menu Name'].unique()

array(['ALL MENUS', 'DRINKS', 'FOOD Short Rib Stewart', nan, 'BRUNCH',
       'DESSERT', 'HAPPY HOUR', 'New Years', 'Special Event',
       'Valentines Day', 'Restaurant Week', 'Brunch Special',
       "Mother's Day", 'Gift Cards', 'Open Items'], dtype=object)

In [40]:
items[['Menu Name', 'Menu Item', "Item Qty (incl voids)"]]

      Menu Name          Menu Item  Item Qty (incl voids)
0     ALL MENUS                NaN                   57.0
1        DRINKS                NaN                   32.0
2        DRINKS                NaN                    2.0
3        DRINKS              Pepsi                    0.0
4        DRINKS         Diet Pepsi                    0.0
..          ...                ...                    ...
455  Gift Cards  Classic Gift Card                    2.0
456  Open Items                NaN                    0.0
457  Open Items                NaN                    0.0
458  Open Items                NaN                    0.0
459  Open Items                NaN                    0.0

[460 rows x 3 columns]

In [43]:
items['Menu Name'].unique()

array(['ALL MENUS', 'DRINKS', 'FOOD Short Rib Stewart', nan, 'BRUNCH',
       'DESSERT', 'HAPPY HOUR', 'New Years', 'Special Event',
       'Valentines Day', 'Restaurant Week', 'Brunch Special',
       "Mother's Day", 'Gift Cards', 'Open Items'], dtype=object)

In [48]:
food = items[items['Menu Name'] == 'FOOD Short Rib Stewart']

In [49]:
food

,Master ID,Item ID,Parent ID,Menu Name,Menu Group,Subgroup,Menu Item,Avg Price,Item Qty (incl voids),% of Ttl Qty (incl voids),...,Discount Amount,Net Amount,# Orders,% of Ttl # Orders,% Qty (Group),% Qty (Menu),% Qty (All),% Net Amt (Group),% Net Amt (Menu),% Net Amt (All)
300,NaN,NaN,NaN,FOOD Short Rib Stewart,NaN,NaN,NaN,12.421053,19.0,0.333333,...,10.4,225.6,7,0.700000,0.000000,0.000000,0.333333,0.000000,0.000000,0.427759
301,2.000000e+17,2.000000e+17,NaN,FOOD Short Rib Stewart,Food,NaN,NaN,12.420000,19.0,1.000000,...,10.4,225.6,7,1.000000,0.000000,1.000000,0.333333,0.000000,1.000000,0.427759
302,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Charcuterie Board,19.000000,1.0,0.052632,...,0.0,19.0,1,0.142857,0.052632,0.052632,0.017544,0.084220,0.084220,0.036026
303,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Stef's Burger,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
304,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Stuffed Mushrooms,8.000000,1.0,0.052632,...,0.0,8.0,1,0.142857,0.052632,0.052632,0.017544,0.035461,0.035461,0.015169
305,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Artichoke Crab Dip,13.000000,1.0,0.052632,...,0.0,13.0,1,0.142857,0.052632,0.052632,0.017544,0.057624,0.057624,0.024649
306,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Mussels,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
307,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Bacon & Eggs,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
308,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,New England Lobster Roll,20.000000,1.0,0.052632,...,0.0,20.0,1,0.142857,0.052632,0.052632,0.017544,0.088652,0.088652,0.037922
309,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,J's Caprese Salad,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
310,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Cauliflower Tacos (V),10.000000,1.0,0.052632,...,0.0,10.0,1,0.142857,0.052632,0.052632,0.017544,0.044326,0.044326,0.018961
311,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Plantain Boat,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
312,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Eggplant Sliders,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
313,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Fall Salad,10.000000,1.0,0.052632,...,0.0,10.0,1,0.142857,0.052632,0.052632,0.017544,0.044326,0.044326,0.018961
314,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Beet Salad,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
315,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Butternut Squash Soup,9.000000,1.0,0.052632,...,0.0,9.0,1,0.142857,0.052632,0.052632,0.017544,0.039894,0.039894,0.017065
316,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Surf & Turf,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
317,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Pesto Pasta (V),22.000000,1.0,0.052632,...,0.0,22.0,1,0.142857,0.052632,0.052632,0.017544,0.097518,0.097518,0.041714
318,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Harvest Chicken,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
319,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Lamb Chops,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
320,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Chicken Wellington,25.000000,1.0,0.052632,...,0.0,25.0,1,0.142857,0.052632,0.052632,0.017544,0.110816,0.110816,0.047402
321,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Butternut Squash Lasagna (V),0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
322,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Scallops,26.000000,2.0,0.105263,...,10.4,41.6,1,0.142857,0.105263,0.105263,0.035088,0.184397,0.184397,0.078878
323,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,J's Burger,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
324,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Side of Fries,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Side of Rissotto,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
326,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Side of Veggies,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
327,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Extra Bread,0.000000,1.0,0.052632,...,0.0,0.0,1,0.142857,0.052632,0.052632,0.017544,0.000000,0.000000,0.000000
328,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Fire Entree,0.000000,4.0,0.210526,...,0.0,0.0,2,0.285714,0.210526,0.210526,0.070175,0.000000,0.000000,0.000000
329,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Add Chicken,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
330,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Add Shrimp,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
331,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Clam Chowder,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
332,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Salmon and Shrimp,23.000000,1.0,0.052632,...,0.0,23.0,1,0.142857,0.052632,0.052632,0.017544,0.101950,0.101950,0.043610
333,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Fire Dessert,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
334,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Mushroom Fries,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
335,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Ribs,17.000000,1.0,0.052632,...,0.0,17.0,1,0.142857,0.052632,0.052632,0.017544,0.075355,0.075355,0.032234
336,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Chicken Noodle Soup,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
337,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Tomatoe Cauliflower Soup,8.000000,1.0,0.052632,...,0.0,8.0,1,0.142857,0.052632,0.052632,0.017544,0.035461,0.035461,0.015169
338,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Taco Skins,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
339,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Meatball Sliders,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
340,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Short Rib Stew,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
341,2.000000e+17,2.000000e+17,2.000000e+17,FOOD Short Rib Stewart,Food,NaN,Seafood Fradiablo,0.000000,0.0,0.000000,...,0.0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [21]:
items[['Menu Item', 'Item Qty (incl voids)']]

             Menu Item  Item Qty (incl voids)
0                  NaN                   57.0
1                  NaN                   32.0
2                  NaN                    2.0
3                Pepsi                    0.0
4           Diet Pepsi                    0.0
..                 ...                    ...
455  Classic Gift Card                    2.0
456                NaN                    0.0
457                NaN                    0.0
458                NaN                    0.0
459                NaN                    0.0

[460 rows x 2 columns]